# Generated by Django 4.1.7 on 2023-03-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.CharField(max_length=250),
        ),
    ]
